name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: integration test ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8.13, 3.9.13, 3.10.6]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install darcs git
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
          darcs --version
      - name: Run integration test
        run: |
          rm -rf _darcs
          poetry run git-darcs update -nw -v -ns
          darcs show tags | grep -q git-checkpoint
          darcs show tags
          rm -rf _darcs
          poetry run git-darcs update -nw -v
          darcs show tags | grep -q git-checkpoint
          darcs show tags
          poetry run git-darcs clone . git-darcs-clone -v
          rm -rf git-darcs-clone
      - name: Run black
        run: poetry run black --check .
      - name: Run flake8
        run: poetry run flake8 --exclude .venv
